# Generated by Django 5.1.2 on 2024-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webku", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Makanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_menu", models.CharField(max_length=100)),
                ("deskripsi", models.TextField()),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gambar", models.ImageField(upload_to="makanan_images/")),
            ],
        ),
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
