# Generated by Django 5.1.3 on 2024-11-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webku", "0003_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
