# Generated by Django 5.1.3 on 2024-11-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webku", "0004_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makanan",
            name="deskripsi",
        ),
    ]
