# Generated by Django 5.1.3 on 2024-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webku", "0005_remove_makanan_deskripsi"),
    ]

    operations = [
        migrations.CreateModel(
            name="makanan2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_menu", models.CharField(max_length=100)),
                ("harga", models.DecimalField(decimal_places=2, max_digits=10)),
                ("gambar", models.ImageField(upload_to="category_makanan/")),
            ],
        ),
    ]
