# Generated by Django 5.1.3 on 2024-11-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webku", "0006_makanan2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="makanan2",
            old_name="nama_menu",
            new_name="nama_category",
        ),
    ]
