# Generated by Django 5.1.3 on 2024-11-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webku", "0008_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
