# Generated by Django 5.0.6 on 2024-12-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0010_makanan2_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='makanan2',
            new_name='Menu',
        ),
        migrations.RenameModel(
            old_name='Makanan',
            new_name='Recommended',
        ),
    ]
