# Generated by Django 5.0.6 on 2024-12-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0011_rename_makanan2_menu_rename_makanan_recommended'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommended',
            new_name='Makanan',
        ),
        migrations.RenameModel(
            old_name='Menu',
            new_name='makanan2',
        ),
    ]
