# Generated by Django 5.0.6 on 2024-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webku', '0014_userprofileadmin_alter_makanan2_category_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan2',
            name='category',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Maccarone', 'Maccarone'), ('Cookies', 'Cookies')], default='', max_length=50),
        ),
    ]
